
dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-5.0
    packages:
      - clang-5.0

script:
  - CXX=clang++-5.0 CC=clang-5.0 cmake . 
  - cmake --build . -- -j2 
  - ctest --output-on-failure -VV
