
dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-6.0
      - llvm-6.0-dev

script:
  - CXX=clang++-6.0 CC=clang-6.0 cmake . 
  - cmake --build . -- -j2 
  - ctest --output-on-failure -VV
