#
# Copyright: 2018 Gerard Choinka (gerard.choinka@gmail.com)
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or
# copy at http://www.boost.org/LICENSE_1_0.txt)
#

language: cpp
os: linux
dist: trusty
sudo: false

cache:
  apt: true
  directories:
    - /home/travis/.hunter
    - /home/travis/opt

matrix:
  include:
    - env: CLANG_VERS="7" CXXCOMPILER="clang++-7" CCOMPILER="clang-7"
      addons: &default_addons
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: [ "clang-7", "llvm-7-dev", "libc++-7-dev", "libc++abi-7-dev", "g++-7", "g++-8", "ninja-build", "xz-utils", "gdb"]
    - env: CMAKE_BUILD_TYPE=Debug CXXCOMPILER=g++-7 CCOMPILER=gcc-7
      addons: *default_addons
    #- env: CMAKE_BUILD_TYPE=Release CXXCOMPILER=g++-8 CCOMPILER=gcc-8
    #  addons: *default_addons
    - env: CMAKE_BUILD_TYPE=Debug CXXCOMPILER=clang++-7 CMAKE_CXX_FLAGS="-fsanitize=undefined -fno-omit-frame-pointer" CMAKE_EXE_LINKER_FLAGS="-fsanitize=undefined" CLANG_VERS="7" CCOMPILER=clang-7 
      addons: *default_addons
    - env: CMAKE_BUILD_TYPE=Release CXXCOMPILER=clang++-7 CCOMPILER=clang-7 CLANG_VERS="7"
      addons: *default_addons
    - env: CMAKE_BUILD_TYPE=Release CXXCOMPILER=clang++-7 CCOMPILER=clang-7 CLANG_VERS="7" CMAKE_CXX_FLAGS="-stdlib=libc++" CMAKE_EXE_LINKER_FLAGS="-lc++ -lc++abi" CMAKE_SHARED_LINKER_FLAGS="-lc++ -lc++abi"
      addons: *default_addons


script:
        #  - mkdir /home/travis/opt/
        #  - wget -qO- "https://github.com/gchoinka/gpm/releases/download/v0.2.0/home_travis_opt_gcc-install.tar.xz" | tar xJ -C /home/travis/opt/
  - test ! -d /home/travis/opt && mkdir /home/travis/opt/ || true
  - export PATH=/usr/lib/llvm-${CLANG_VERS}/bin/:${PATH}
  - export ASAN_OPTIONS=symbolize=1
  - export LSAN_OPTIONS=verbosity=1:log_threads=1
  - rm -rf /home/travis/opt/cmake-* 2> /dev/null || true
  - wget -qO- "https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.tar.gz" | tar xz -C /home/travis/opt/ &> /dev/null
  - export CMAKE_BIN=$(echo /home/travis/opt/cmake-*/bin/cmake)
  - export CTEST_BIN=$(echo /home/travis/opt/cmake-*/bin/ctest)
  - find / -path "*/include/c++/v1" 2> /dev/null || true
  - |
    mkdir build
    cd build
    ${CMAKE_BIN} .. -GNinja \
      -DCMAKE_CXX_COMPILER="${CXXCOMPILER}" \
      -DCMAKE_C_COMPILER="${CCCOMPILER}" \
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
      -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}" \
      -DCMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS}" \
      -DCMAKE_SHARED_LINKER_FLAGS="${CMAKE_SHARED_LINKER_FLAGS}"
  - ${CMAKE_BIN} --build . -- -j2 
  - ctest --output-on-failure -VV        
  - ${CMAKE_BIN} --build . --target run_tree_benchmark
