
dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-5.0
      - llvm-5.0-dev

script:
  - CXX=clang++-5.0 CC=clang-5.0 cmake . 
  - cmake --build . -- -j2 
  - ctest --output-on-failure -VV
