version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      FLAGS: "/permissive- /std:c++latest /utf-8 /F 16777216"
      GENERATOR: Visual Studio 15 2017
      APPVEYOR_SAVE_CACHE_ON_ERROR: true

cache: 
  - C:\.hunter
  
init:
  - cmake --version
  - msbuild /version

before_build:
  - cmake . -G "%GENERATOR%" -DCMAKE_CXX_FLAGS="%FLAGS%" -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"

build_script:
  - cmake --build .

test_script:
#  - cmake --build . --target make_tree_benchmark
#  - C:\projects\gpm\examples\ant\Debug\generate_tree_for_benchmark.exe
#  - ctest --output-on-failure -VV -C Debug .
